# Generated by Django 4.1.7 on 2023-04-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student_registration", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_name",
        ),
    ]
