# Generated by Django 4.1.7 on 2023-04-09 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student_registration", "0002_remove_user_user_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driverprofile",
            name="assigned_route",
        ),
        migrations.CreateModel(
            name="Routes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "driver",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_registration.driverprofile",
                    ),
                ),
            ],
        ),
    ]
