# Generated by Django 4.1.7 on 2023-04-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_registration", "0003_remove_driverprofile_assigned_route_routes"),
    ]

    operations = [
        migrations.AddField(
            model_name="routes",
            name="included_route",
            field=models.CharField(
                choices=[("routeA", "route A"), ("routeB", " route B")],
                default="routeA",
                max_length=100,
            ),
        ),
    ]
